apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prithvi-sen1floods11-monitor
  namespace: prithvi-kserve
  labels:
    app: prithvi-sen1floods11
spec:
  selector:
    matchLabels:
      serving.kserve.io/inferenceservice: prithvi-sen1floods11
  podMetricsEndpoints:
    - targetPort: 8000
      path: /metrics
      interval: 30s
      scheme: http
