apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: prithvi-sen1floods11
  namespace: prithvi-kserve
  annotations:
    serving.kserve.io/deploymentMode: "RawDeployment"
    serving.kserve.io/autoscalerClass: "keda"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"
    prometheus.io/scheme: "http"
  labels:
    networking.kserve.io/visibility: exposed
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 5

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values:
                    - "adcpu105"

    # --- KEDA Configuration ---
    # KServe will automatically create a ScaledObject based on this block
    autoScaling:
      metrics:
        - type: External
          external:
            metric:
              backend: "prometheus"
              serverAddress: "https://thanos-querier.openshift-monitoring.svc:9091"
              query: "sum(rate(vllm:request_success_total[1m]))"
            authenticationRef:
              authenticationRef:
                name: thanos-reader-trigger-auth
              authModes: bearer
            target:
              type: Value
              value: 5

    containers:
      - name: vllm
        image: quay.io/alessandropomponio_ibm/vllm:vllm-v0.18.0-tt-v1.2.5
        command: ["vllm", "serve"]
        args:
          - "ibm-nasa-geospatial/Prithvi-EO-2.0-300M-TL-Sen1Floods11"
          - "--skip-tokenizer-init"
          - "--enable-mm-embeds"
          - "--io-processor-plugin"
          - "terratorch_segmentation"
          - "--max-num-seqs"
          - "1"
          - "--enforce-eager"
        env:
          # Optional: where HF caches downloaded weights; useful with an attached volume.
          - name: HF_HOME
            value: "/models/hf"
          - name: HOME
            value: "/vllm-home"

        ports:
          - containerPort: 8000

        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          periodSeconds: 2

        resources:
          limits:
            cpu: "64"
            memory: 64G
            nvidia.com/gpu: "1"
          requests:
            cpu: "32"
            memory: 64G
            nvidia.com/gpu: "1"

        # Optional: cache HF downloads across restarts (recommended for workshops).
        volumeMounts:
          - name: model-cache
            mountPath: /models
          - name: home-dir
            mountPath: /vllm-home

    volumes:
      - name: model-cache
        persistentVolumeClaim:
          claimName: model-cache-pvc
      - name: home-dir
        emptyDir: {}
